[project]
name = "farmsetu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "django>=4.2.20",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.0",
]
