# Generated by Django 4.2.20 on 2025-04-24 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthWiseTempratureDbModel',
            fields=[
                ('record_created_at', models.DateTimeField(auto_now_add=True)),
                ('record_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.CharField(choices=[('uk', 'uk'), ('england', 'england'), ('wales', 'wales'), ('scotland', 'scotland'), ('northern_ireland', 'northern_ireland'), ('england_and_wales', 'england_and_wales'), ('england_n', 'england_n'), ('england_s', 'england_s'), ('scotland_n', 'scotland_n'), ('scotland_e', 'scotland_e'), ('scotland_w', 'scotland_w'), ('england_e_and_ne', 'england_e_and_ne'), ('england_nw_and_n_wales', 'england_nw_and_n_wales'), ('midlands', 'midlands'), ('east_anglia', 'east_anglia'), ('england_sw_and_s_wales', 'england_sw_and_s_wales'), ('england_se_and_central_s', 'england_se_and_central_s')], max_length=30, null=True)),
                ('month', models.CharField(choices=[('jan', 'jan'), ('feb', 'feb'), ('mar', 'mar'), ('apr', 'apr'), ('may', 'may'), ('jun', 'jun'), ('jul', 'jul'), ('aug', 'aug'), ('sep', 'sep'), ('oct', 'oct'), ('nov', 'nov'), ('dec', 'dec')], max_length=5, null=True)),
                ('temperature', models.CharField(max_length=6, null=True)),
                ('year', models.CharField(max_length=4, null=True)),
            ],
            options={
                'verbose_name_plural': 'Month Wise Temprature',
            },
        ),
        migrations.CreateModel(
            name='SeasonWiseTempratureDbModel',
            fields=[
                ('record_created_at', models.DateTimeField(auto_now_add=True)),
                ('record_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.CharField(choices=[('uk', 'uk'), ('england', 'england'), ('wales', 'wales'), ('scotland', 'scotland'), ('northern_ireland', 'northern_ireland'), ('england_and_wales', 'england_and_wales'), ('england_n', 'england_n'), ('england_s', 'england_s'), ('scotland_n', 'scotland_n'), ('scotland_e', 'scotland_e'), ('scotland_w', 'scotland_w'), ('england_e_and_ne', 'england_e_and_ne'), ('england_nw_and_n_wales', 'england_nw_and_n_wales'), ('midlands', 'midlands'), ('east_anglia', 'east_anglia'), ('england_sw_and_s_wales', 'england_sw_and_s_wales'), ('england_se_and_central_s', 'england_se_and_central_s')], max_length=30, null=True)),
                ('season', models.CharField(choices=[('win', 'win'), ('spr', 'spr'), ('sum', 'sum'), ('aut', 'aut'), ('ann', 'ann')], max_length=5, null=True)),
                ('temperature', models.CharField(max_length=6, null=True)),
                ('year', models.CharField(max_length=4, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
