# Generated by Django 4.2.20 on 2025-04-29 03:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionDBModel',
            fields=[
                ('record_created_at', models.DateTimeField(auto_now_add=True)),
                ('record_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Regions',
                'unique_together': {('region',)},
            },
        ),
        migrations.CreateModel(
            name='SeasonDbModel',
            fields=[
                ('record_created_at', models.DateTimeField(auto_now_add=True)),
                ('record_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('season', models.CharField(max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Seasons',
                'unique_together': {('season',)},
            },
        ),
        migrations.CreateModel(
            name='SeasonWiseTempratureDbModel',
            fields=[
                ('record_created_at', models.DateTimeField(auto_now_add=True)),
                ('record_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('temperature', models.CharField(max_length=6, null=True)),
                ('year', models.CharField(max_length=4, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.regiondbmodel')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seasondbmodel')),
            ],
            options={
                'verbose_name_plural': 'Season Wise Temprature',
                'unique_together': {('year', 'season', 'region')},
            },
        ),
        migrations.CreateModel(
            name='MonthWiseTempratureDbModel',
            fields=[
                ('record_created_at', models.DateTimeField(auto_now_add=True)),
                ('record_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('month', models.CharField(max_length=5, null=True)),
                ('temperature', models.CharField(max_length=6, null=True)),
                ('year', models.CharField(max_length=4, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.regiondbmodel')),
            ],
            options={
                'verbose_name_plural': 'Month Wise Temprature',
                'unique_together': {('year', 'month', 'region')},
            },
        ),
    ]
